package checks

// DefaultStepNames lists the default step names that are used if the step name is not specifically supplied.
var DefaultStepNames = []string{
	"Run a Script",
	"Run an Azure Script",
	"Run an AWS CLI Script",
	"Run gcloud in a Script",
	"Deploy an Azure Resource Manager template",
	"Run a Service Fabric SDK PowerShell Script",
	"Run a kubectl CLI Script",
	"Deploy a Package",
	"Deploy to IIS",
	"Deploy a Windows Service",
	"Deploy an Azure Web App (Web Deploy)",
	"Deploy a Service Fabric App",
	"Deploy an Azure Cloud Service",
	"Upload a package to an AWS S3 bucket",
	"Deploy to NGINX",
	"Transfer a Package",
	"Deploy Java Archive",
	"Deploy a VHD",
	"Deploy Amazon ECS Service",
	"Update Amazon ECS Service",
	"Deploy an AWS CloudFormation template",
	"Apply an AWS CloudFormation Change Set",
	"Delete an AWS CloudFormation stack",
	"Upload a package to an AWS S3 bucket",
	"Deploy a Bicep template",
	"Deploy an Azure App Service",
	"Import Certificate",
	"Deploy a certificate to Tomcat",
	"Configure certificate for WildFly or EAP",
	"Deploy a keystore to the filesystem",
	"Create a Docker Network",
	"Run a Docker Container",
	"Stop a Docker Resource",
	"Deploy Java Archive",
	"Deploy to Tomcat via Manager",
	"Start/Stop App in Tomcat",
	"Deploy to WildFly or EAP",
	"Enable/Disable deployment in WildFly or EAP",
	"Deploy raw Kubernetes YAML",
	"Kustomize",
	"Upgrade a Helm Chart",
	"Deploy Kubernetes containers",
	"Deploy Kubernetes config map resource",
	"Deploy Kubernetes ingress resource",
	"Deploy Kubernetes secret resource",
	"Apply a Terraform template",
	"Destroy Terraform resources",
	"Plan to apply a Terraform template",
	"Plan a Terraform destroy",
	"Send an Email",
	"Health Check",
	"Manual Intervention Required",
	"Deploy a Release",
	"Jira Service Desk Change Request",
}
